name: Build & Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: read       
  packages: write      
  id-token: write      

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. get the version from the tag
      - name: Determine image tag
        id: tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      # 4. build and push Docker image
      - name: Build and push app-frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.TAG }}
            ghcr.io/${{ github.repository }}:latest